version: '3.8'

services:
  rathole:
    image: rapiz1/rathole:v0.5.0
    command: --server /config/rathole.server.toml
    restart: unless-stopped
    ports:
      - 2333:2333
      - 80:5080
      - 443:5443
      # host:container
    volumes:
      - ./rathole.server.toml:/config/server.toml:ro
